### ISSUE TITLE
Crash client when moving or being in the winter season.

### ISSUE THREAD

**Issue by Khikki** [DarkShadow44/SereneSeasons#5] opened 2020-01-18 11:07 UTC
Crash client when moving or being in the winter season.

[crash-2020-01-18_00.01.31-client.txt](https://github.com/DarkShadow44/SereneSeasons/files/4080442/crash-2020-01-18_00.01.31-client.txt)

**Comment by DarkShadow44** [comment] 2020-01-26 22:07
I'm yet to investigate this, will look into it when I find time.

**Comment by DarkShadow44** [comment] 2020-02-21 16:38
Can you give simple steps to reproduce?

**Comment by Khikki** [comment] 2020-02-22 19:33
Sure. Prescribe /ss setseason MID_WINTER, /weather rain, start flying around the world.

**Comment by DarkShadow44** [comment] 2020-02-22 21:03
I tried, but no crash. According to the log, the issue seems to happen in conjunction with twilightforest. Does it happen with only SereneSeasons as well?

I need a way to reliably reproduce the issue, otherwise I can't fix it. Minimal setup with preferably only SereneSeasons and the mods that cause the issue would be good, including a world seed.

**Comment by Dundy733** [comment] 2020-04-11 20:08
Hello, I have the same issue. From my expirience, the game crashes during LATE_WINTER. I have multiple mods running so it can be some mod incompatibility issue. I would guess it is related to Extreme Biomes mod because I have my base in one of its biomes.

**Comment by DarkShadow44** [comment] 2020-04-12 00:48
Could you please try to find out which mod it is? Just copy the world and then find the minimal setup to reproduce the issue. As long as I can't reproduce, I can't address it.

**Comment by Dundy733** [comment] 2020-04-12 07:51
Well I have over 100 mods running, this may take a while. Guess I will try the ones adding biomes first. Because from what I have found about the crash report it looks like some sort of broken chunk.

**Comment by Dundy733** [comment] 2020-04-12 08:41
I have found something. It seem that The Twilight Forest is causing this. It is weird because I got the crash in the overworld and only dim 0 could be affected by seasons. I have minimalized my modpack to 5 mods and I will try to find the one or the combination of them causing this.

**Comment by Dundy733** [comment] 2020-04-13 12:09
So far it looks like the combination of following mods is causing that: extrabiomesXL(3.16.4), twilightforest (2.3.7), sereneseasons, liteloader and mod_voxelMap (liteloader version). I tried to remove voxelMap, reload the world (with previous error) and it was ok. Also when I have removed extremebiomes with voxelMap running. When I add it all back, the world shuts down the whole client again. So this is the combination causing exrror in my case.

**Comment by DarkShadow44** [comment] 2020-04-13 16:35
Strange combination, but thanks for finding that! Could you send me a copy of a crashing world?

**Comment by Dundy733** [comment] 2020-04-13 17:25
[crash.zip](https://github.com/DarkShadow44/SereneSeasons/files/4470662/crash.zip)
At first I went to coordinates -4300, 300, 94 where my base in my modpack is located and run the command. After a minute or two of wandering around the game crashed.
But this issue seems more tricky than I thought. I tried to recreate the world just once more and try to set LATE_WINTER again but I got only a few lag spikes but no crash. I am sorry to bother you with these unclear results but maybe you'll be able to find that problem while I'll do some more experiments.

**Comment by DarkShadow44** [comment] 2020-04-13 19:24
Thanks for your effort, helped me finally track this down!
The problem is that certain Minecraft classes can't deal with negative temperatures, which might occur in winter. In combination with TwilightForest and VoxelMap those classes are called, and result in crashes.
I pushed a fix that should address these issues.

**Closed as completed by DarkShadow44** 2020-04-13 19:24 UTC

**Comment by Dundy733** [comment] 2020-04-13 20:20
I am glad to hear that. Will this new fix be avalaible for download at CurseForge or somewhere else?

**Comment by DarkShadow44** [comment] 2020-04-13 20:38
Only through compiling from source, I'm afraid. I'm not allowed to distribute binaries.

**Comment by Dundy733** [comment] 2020-04-13 21:06
Well I am newbie on GitHub so i don't know how things work here but somebody was able to upload the previous 1.7.10 version at CurseForge with note that it is unofficial version. Is there a way to contact him and post it somewhere? It would be really nice to have my modpack fully working again and I think there are others that would appreciate it. Or am I able to compile it somehow and us it for my own needs?

**Comment by DarkShadow44** [comment] 2020-04-13 23:21
You can compile from source, see https://github.com/DarkShadow44/SereneSeasons/blob/1.7.10_backport/README.md

The problem here is copyright. The owners of the mod allowed be to do a backport, but I'm not allowed to distribute it.

**Comment by Dundy733** [comment] 2020-04-14 08:48
I tried that but I got this error. 
![image](https://user-images.githubusercontent.com/63517817/79204843-789ecf80-7e3d-11ea-9ca1-7774884fc546.png)

**Comment by Dundy733** [comment] 2020-04-14 09:41
Thak you very much. I will try this new build and report any other issue here.

**Comment by DarkShadow44** [comment] 2020-04-14 19:14
@Dundy733 You must use Java 8.

**Comment by Dundy733** [comment] 2020-04-14 19:46
Yes. It's all working now.
