### ISSUE TITLE
Leaves and Grass no longer change with the seasons

### ISSUE THREAD

**Issue by 062regrahc** [DarkShadow44/SereneSeasons#12] opened 2020-02-21 19:09 UTC
as of the commit that fixed the XZ coordinate issue, leaves and tall grass no longer change with the seasons, but plants like vines still do. here's are some screenshots with the problem in swamplands, mid winter and mid-autumn, as an example
![2020-02-21_14 06 04](https://user-images.githubusercontent.com/16433640/75063676-5cbd2400-54b3-11ea-82e4-8d6d6d6c5931.png)
![2020-02-21_14 07 44](https://user-images.githubusercontent.com/16433640/75063807-a86fcd80-54b3-11ea-99ff-c8c3196ae43a.png)

**Comment by DarkShadow44** [comment] 2020-02-22 12:58
Thanks, how did I miss that? The issue is with the fix for DragonAPI. I'll fix that.

**Comment by DarkShadow44** [comment] 2020-02-22 13:39
I pushed a fix. Sorry for missing that one, really dislike how the obfuscation makes development so much harder. Since I moved the ASM transformer to the end, we need to operate on (partially) debfuscated names, changing up everything.

**Closed as completed by DarkShadow44** 2020-02-22 13:39 UTC
